@tool
extends EditorPlugin

func _enter_tree():
	# Initialization of the plugin goes here.
	pass

func _build() -> bool:
	var path: String = "res://nova/sources/gdscript/runtime/"
	var output_path: String = "res://nova/sources/gdscript/runtime_block.gd"

	print_verbose("Fetching compatible mapping from runtime sources...")

	var dir: DirAccess = DirAccess.open(path)
	if not dir:
		printerr("Failed to open directory:", path)
		return false

	var files: Array[String] = []
	dir.list_dir_begin()
	while true:
		var file: String = dir.get_next()
		if file == "":
			break
		if file.get_extension() == "gd":
			files.append(file)

	dir.list_dir_end()

	var func_mappings: Dictionary = {}
	var var_mappings: Dictionary  = {}


	var class_regex = RegEx.new()
	class_regex.compile("class_name ([A-Za-z0-9_]+)")

	var var_regex = RegEx.new()
	var_regex.compile("#@export\nstatic var ([A-Za-z0-9_]+)")

	var func_regex = RegEx.new()
	func_regex.compile("#@export\nstatic func ([A-Za-z0-9_]+)")

	var module_list: Array[Variant] = []

	for file in files:
		var text: String = FileAccess.open(path + file, FileAccess.READ).get_as_text()
		var cls_name     = class_regex.search(text)
		if not cls_name:
			continue

		var cls = cls_name.get_string(1)

		var exports: Array = []
		var export                  = var_regex.search(text)
		while export:
			var name = export.get_string(1)
			exports.append(name)
			export = var_regex.search(text, export.get_end())
		if exports.size() > 0:
			var_mappings[cls] = exports

		exports = []
		export = func_regex.search(text)
		while export:
			var name = export.get_string(1)
			var start     = export.get_end()
			var end: int          = text.find(")", start)
			var signature: String = text.substr(start, end - start)
			signature = signature.lstrip("(").rstrip(")")
			# Long signatures get wrapped across multiple source lines (continuation line
			# indented with a tab, no ", " on the break) - collapse all whitespace runs
			# (including the newline) to a single space before this gets comma-split below,
			# or whichever param sits right after the line break gets silently merged into
			# its predecessor and dropped from the generated forwarding call.
			signature = signature.replace("\n", " ").replace("\t", " ")
			while signature.find("  ") != -1:
				signature = signature.replace("  ", " ")
			# GDScript's static checker hard-errors on "return <call to a -> void function>"
			# (not just a warning) - the forwarder can only use "return" when the source
			# function itself isn't declared "-> void". Detected from the literal text between
			# the closing paren and the body colon, e.g. "-> Variant:" vs plain ":".
			var colon_pos: int       = text.find(":", end)
			var return_type: String = text.substr(end + 1, colon_pos - end - 1).strip_edges()
			var is_void: bool        = return_type == "" or return_type.find("void") != -1
			exports.append({"name": name, "signature": signature, "is_void": is_void})
			export = func_regex.search(text, end)
		if exports.size() > 0:
			func_mappings[cls] = exports

		if cls in func_mappings or cls in var_mappings:
			module_list.append(cls)

	var output: FileAccess = FileAccess.open(output_path, FileAccess.WRITE)
	if not output:
		printerr("Failed to open file for writing:", output_path)
		return false

	output.store_string("# This file is generated by the Nova Engine. Do not modify.\n\n")
	output.store_string("class_name RuntimeBlock extends RefCounted\n\n")

	for cls in module_list:
		output.store_string("## " + cls + "\n")

		if cls in var_mappings:
			for export in var_mappings[cls]:
				output.store_string("static var " + export + ":\n\t")
				output.store_string("get: return " + cls + "." + export + "\n\t")
				output.store_string("set(value): " + cls + "." + export + " = value\n")

		if cls in func_mappings:
			for export in func_mappings[cls]:
				output.store_string("func " + export["name"] + "(" + export["signature"] + "):\n\t")
				# Forward via "return" so #@export functions that now return the queued
				# AnimationEntry (for chaining) propagate it through the wrapper - but GDScript's
				# static checker hard-errors on "return <call to a -> void function>", so this
				# must stay conditional on the source's own declared return type (is_void, above).
				if not export["is_void"]:
					output.store_string("return ")
				output.store_string(cls + "." + export["name"] + "(")
				var params                     = export["signature"].split(", ")
				var param_list: Array[Variant] = []
				for param in params:
					var parts = param.split(":")
					if parts.size() > 1:
						param_list.append(parts[0])
					else:
						parts = param.split("=")
						if parts.size() > 1:
							param_list.append(parts[0])
						else:
							param_list.append(param)
				output.store_string(", ".join(param_list))
				output.store_string(")\n")

		output.store_string("\n")

	return true

func _exit_tree():
	# Clean-up of the plugin goes here.
	pass
